package br.edu.iftm.pv_projetoimobiliaria_pt2.view;

import java.awt.CardLayout;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author AFSOUZA
 */
public class Telas extends javax.swing.JFrame {
    
      
    CardLayout cl;
 



    /**
     * Creates new form Telas
     */
    public Telas() {
        initComponents();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        SistemaTelaInicial = new javax.swing.JPanel();
        lbSistema = new javax.swing.JLabel();
        UsuarioCriarEditar = new javax.swing.JPanel();
        criarUsuarioPanel = new javax.swing.JPanel();
        id = new javax.swing.JLabel();
        cpf = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        idUsuarioField = new javax.swing.JTextField();
        nomeField = new javax.swing.JTextField();
        telefone = new javax.swing.JLabel();
        enviarUsuarioButton = new javax.swing.JButton();
        cancelUsuarioButton = new javax.swing.JButton();
        cpfField = new javax.swing.JFormattedTextField();
        telefoneField = new javax.swing.JFormattedTextField();
        lbTituloUsuarioCriar = new javax.swing.JLabel();
        UsuarioExcluirListar = new javax.swing.JPanel();
        lbUsuarioExcluir = new javax.swing.JLabel();
        ContratoCriarEditar = new javax.swing.JPanel();
        lbTituloContratoCriar = new javax.swing.JLabel();
        criarContratoPanel = new javax.swing.JPanel();
        idContrato = new javax.swing.JLabel();
        cpf1 = new javax.swing.JLabel();
        cliente = new javax.swing.JLabel();
        idContratoField = new javax.swing.JTextField();
        imovelContratoField = new javax.swing.JTextField();
        clienteContratoField = new javax.swing.JTextField();
        dataContrato = new javax.swing.JLabel();
        enviarContratoButton = new javax.swing.JButton();
        cancelContratoButton = new javax.swing.JButton();
        dataFinalizacao = new javax.swing.JLabel();
        statusContrato = new javax.swing.JLabel();
        statusContratoField = new javax.swing.JTextField();
        dataContratoTextField = new javax.swing.JFormattedTextField();
        dataFinalContratoTextField = new javax.swing.JFormattedTextField();
        ContratoExcluirListar = new javax.swing.JPanel();
        lbTituloContratoExcluir = new javax.swing.JLabel();
        ImovelCriarEditar = new javax.swing.JPanel();
        lbTituloImovelCriar = new javax.swing.JLabel();
        criarImovelPanel = new javax.swing.JPanel();
        idImovel = new javax.swing.JLabel();
        tipoImovel = new javax.swing.JLabel();
        precoImovel = new javax.swing.JLabel();
        enderecoImovel = new javax.swing.JLabel();
        idImovelField = new javax.swing.JTextField();
        enderecoImovelField = new javax.swing.JTextField();
        enviarImovelButton = new javax.swing.JButton();
        cancelImovelButton = new javax.swing.JButton();
        precoField = new javax.swing.JFormattedTextField();
        tipoImovelComboBox = new javax.swing.JComboBox<>();
        ImovelExcluirListar = new javax.swing.JPanel();
        lbTituloImovelExcluir = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jmSistema = new javax.swing.JMenu();
        jmSistemaTelaInicial = new javax.swing.JMenuItem();
        jmSistemaSair = new javax.swing.JMenuItem();
        jmUsuario = new javax.swing.JMenu();
        jmUsuarioCriar = new javax.swing.JMenuItem();
        jmUsuarioEditar = new javax.swing.JMenuItem();
        jmCliente = new javax.swing.JMenu();
        jmClienteCadastrar = new javax.swing.JMenuItem();
        jmClienteEditar = new javax.swing.JMenuItem();
        jmImovel = new javax.swing.JMenu();
        jmImovelCadastrar = new javax.swing.JMenuItem();
        jmImovelEditar = new javax.swing.JMenuItem();
        jmContrato = new javax.swing.JMenu();
        jmContratoCriar = new javax.swing.JMenuItem();
        jmContratoListar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));

        MainPanel.setPreferredSize(new java.awt.Dimension(1280, 720));
        MainPanel.setLayout(new java.awt.CardLayout());

        lbSistema.setText("Card - Tela Inicial");

        javax.swing.GroupLayout SistemaTelaInicialLayout = new javax.swing.GroupLayout(SistemaTelaInicial);
        SistemaTelaInicial.setLayout(SistemaTelaInicialLayout);
        SistemaTelaInicialLayout.setHorizontalGroup(
            SistemaTelaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SistemaTelaInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbSistema)
                .addContainerGap(1182, Short.MAX_VALUE))
        );
        SistemaTelaInicialLayout.setVerticalGroup(
            SistemaTelaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SistemaTelaInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbSistema)
                .addContainerGap(698, Short.MAX_VALUE))
        );

        MainPanel.add(SistemaTelaInicial, "card2");

        criarUsuarioPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Criar Usuário"));

        id.setText("ID:");

        cpf.setText("CPF:");

        nome.setText("Nome completo:");

        idUsuarioField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idUsuarioFieldActionPerformed(evt);
            }
        });

        nomeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFieldActionPerformed(evt);
            }
        });

        telefone.setText("Telefone:");

        enviarUsuarioButton.setText("Enviar");

        cancelUsuarioButton.setText("Cancelar");

        try {
            cpfField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            telefoneField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout criarUsuarioPanelLayout = new javax.swing.GroupLayout(criarUsuarioPanel);
        criarUsuarioPanel.setLayout(criarUsuarioPanelLayout);
        criarUsuarioPanelLayout.setHorizontalGroup(
            criarUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, criarUsuarioPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(enviarUsuarioButton)
                .addGap(18, 18, 18)
                .addComponent(cancelUsuarioButton)
                .addGap(36, 36, 36))
            .addGroup(criarUsuarioPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(criarUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(criarUsuarioPanelLayout.createSequentialGroup()
                        .addGroup(criarUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cpf)
                            .addComponent(telefone))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(criarUsuarioPanelLayout.createSequentialGroup()
                        .addGroup(criarUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nome)
                            .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                        .addGroup(criarUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id)
                            .addGroup(criarUsuarioPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(idUsuarioField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(113, 113, 113))
                    .addGroup(criarUsuarioPanelLayout.createSequentialGroup()
                        .addGroup(criarUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cpfField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        criarUsuarioPanelLayout.setVerticalGroup(
            criarUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(criarUsuarioPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(criarUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, criarUsuarioPanelLayout.createSequentialGroup()
                        .addComponent(nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(criarUsuarioPanelLayout.createSequentialGroup()
                        .addComponent(id)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idUsuarioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpfField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(telefone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addGroup(criarUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enviarUsuarioButton)
                    .addComponent(cancelUsuarioButton))
                .addGap(20, 20, 20))
        );

        lbTituloUsuarioCriar.setText("Card - Usuário Criar");

        javax.swing.GroupLayout UsuarioCriarEditarLayout = new javax.swing.GroupLayout(UsuarioCriarEditar);
        UsuarioCriarEditar.setLayout(UsuarioCriarEditarLayout);
        UsuarioCriarEditarLayout.setHorizontalGroup(
            UsuarioCriarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioCriarEditarLayout.createSequentialGroup()
                .addGroup(UsuarioCriarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UsuarioCriarEditarLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lbTituloUsuarioCriar))
                    .addGroup(UsuarioCriarEditarLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(criarUsuarioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        UsuarioCriarEditarLayout.setVerticalGroup(
            UsuarioCriarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UsuarioCriarEditarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbTituloUsuarioCriar)
                .addGap(81, 81, 81)
                .addComponent(criarUsuarioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        MainPanel.add(UsuarioCriarEditar, "card2");

        lbUsuarioExcluir.setText("Card - Usuario Editar/Listar/Excluir");

        javax.swing.GroupLayout UsuarioExcluirListarLayout = new javax.swing.GroupLayout(UsuarioExcluirListar);
        UsuarioExcluirListar.setLayout(UsuarioExcluirListarLayout);
        UsuarioExcluirListarLayout.setHorizontalGroup(
            UsuarioExcluirListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioExcluirListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbUsuarioExcluir)
                .addContainerGap(1092, Short.MAX_VALUE))
        );
        UsuarioExcluirListarLayout.setVerticalGroup(
            UsuarioExcluirListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioExcluirListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbUsuarioExcluir)
                .addContainerGap(698, Short.MAX_VALUE))
        );

        MainPanel.add(UsuarioExcluirListar, "card2");

        lbTituloContratoCriar.setText("Card - Contrato Criar/Editar");

        criarContratoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Novo Contrato"));

        idContrato.setText("ID Contrato:");

        cpf1.setText("Imóvel:");

        cliente.setText("Cliente:");

        idContratoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idContratoFieldActionPerformed(evt);
            }
        });

        imovelContratoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imovelContratoFieldActionPerformed(evt);
            }
        });

        clienteContratoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteContratoFieldActionPerformed(evt);
            }
        });

        dataContrato.setText("Data do Contrato:");

        enviarContratoButton.setText("Enviar");
        enviarContratoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarContratoButtonActionPerformed(evt);
            }
        });

        cancelContratoButton.setText("Cancelar");

        dataFinalizacao.setText("Data de Finalização:");

        statusContrato.setText("Status");

        statusContratoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusContratoFieldActionPerformed(evt);
            }
        });

        try {
            dataContratoTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataContratoTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        try {
            dataFinalContratoTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataFinalContratoTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout criarContratoPanelLayout = new javax.swing.GroupLayout(criarContratoPanel);
        criarContratoPanel.setLayout(criarContratoPanelLayout);
        criarContratoPanelLayout.setHorizontalGroup(
            criarContratoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, criarContratoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(enviarContratoButton)
                .addGap(18, 18, 18)
                .addComponent(cancelContratoButton)
                .addGap(36, 36, 36))
            .addGroup(criarContratoPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(criarContratoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(criarContratoPanelLayout.createSequentialGroup()
                        .addGroup(criarContratoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataFinalizacao)
                            .addComponent(statusContrato)
                            .addComponent(cpf1)
                            .addComponent(dataContrato)
                            .addComponent(cliente))
                        .addGap(558, 819, Short.MAX_VALUE))
                    .addGroup(criarContratoPanelLayout.createSequentialGroup()
                        .addGroup(criarContratoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusContratoField, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idContratoField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clienteContratoField, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imovelContratoField, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idContrato)
                            .addComponent(dataContratoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataFinalContratoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        criarContratoPanelLayout.setVerticalGroup(
            criarContratoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(criarContratoPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(idContrato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idContratoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clienteContratoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpf1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imovelContratoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataContrato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataContratoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataFinalizacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataFinalContratoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(statusContrato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusContratoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(criarContratoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enviarContratoButton)
                    .addComponent(cancelContratoButton))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout ContratoCriarEditarLayout = new javax.swing.GroupLayout(ContratoCriarEditar);
        ContratoCriarEditar.setLayout(ContratoCriarEditarLayout);
        ContratoCriarEditarLayout.setHorizontalGroup(
            ContratoCriarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContratoCriarEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloContratoCriar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContratoCriarEditarLayout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addComponent(criarContratoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );
        ContratoCriarEditarLayout.setVerticalGroup(
            ContratoCriarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContratoCriarEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloContratoCriar)
                .addGap(94, 94, 94)
                .addComponent(criarContratoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        MainPanel.add(ContratoCriarEditar, "card2");

        lbTituloContratoExcluir.setText("Card - Contrato Editar/Listar/Excluir");

        javax.swing.GroupLayout ContratoExcluirListarLayout = new javax.swing.GroupLayout(ContratoExcluirListar);
        ContratoExcluirListar.setLayout(ContratoExcluirListarLayout);
        ContratoExcluirListarLayout.setHorizontalGroup(
            ContratoExcluirListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContratoExcluirListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloContratoExcluir)
                .addContainerGap(1085, Short.MAX_VALUE))
        );
        ContratoExcluirListarLayout.setVerticalGroup(
            ContratoExcluirListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContratoExcluirListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloContratoExcluir)
                .addContainerGap(698, Short.MAX_VALUE))
        );

        MainPanel.add(ContratoExcluirListar, "card2");

        lbTituloImovelCriar.setText("Card - Imovel Criar/Editar");

        criarImovelPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Criar Imóvel"));

        idImovel.setText("ID:");

        tipoImovel.setText("Tipo de Imóvel:");

        precoImovel.setText("Preço:");

        enderecoImovel.setText("Endereço:");

        idImovelField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idImovelFieldActionPerformed(evt);
            }
        });

        enderecoImovelField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoImovelFieldActionPerformed(evt);
            }
        });

        enviarImovelButton.setText("Enviar");

        cancelImovelButton.setText("Cancelar");

        try {
            precoField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("R$####,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        tipoImovelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa", "Apartamento", "Imóvel Comercial", "Lote", "Rural", "Outro" }));
        tipoImovelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoImovelComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout criarImovelPanelLayout = new javax.swing.GroupLayout(criarImovelPanel);
        criarImovelPanel.setLayout(criarImovelPanelLayout);
        criarImovelPanelLayout.setHorizontalGroup(
            criarImovelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, criarImovelPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(enviarImovelButton)
                .addGap(18, 18, 18)
                .addComponent(cancelImovelButton)
                .addGap(36, 36, 36))
            .addGroup(criarImovelPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(criarImovelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(criarImovelPanelLayout.createSequentialGroup()
                        .addGroup(criarImovelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(precoImovel)
                            .addComponent(tipoImovel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(criarImovelPanelLayout.createSequentialGroup()
                        .addComponent(precoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(criarImovelPanelLayout.createSequentialGroup()
                        .addGroup(criarImovelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tipoImovelComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(enderecoImovel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enderecoImovelField, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addGroup(criarImovelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idImovel)
                            .addComponent(idImovelField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(119, 119, 119))))
        );
        criarImovelPanelLayout.setVerticalGroup(
            criarImovelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(criarImovelPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(criarImovelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(criarImovelPanelLayout.createSequentialGroup()
                        .addComponent(enderecoImovel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enderecoImovelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(criarImovelPanelLayout.createSequentialGroup()
                        .addComponent(idImovel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idImovelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(precoImovel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(precoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(tipoImovel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoImovelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addGroup(criarImovelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enviarImovelButton)
                    .addComponent(cancelImovelButton))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout ImovelCriarEditarLayout = new javax.swing.GroupLayout(ImovelCriarEditar);
        ImovelCriarEditar.setLayout(ImovelCriarEditarLayout);
        ImovelCriarEditarLayout.setHorizontalGroup(
            ImovelCriarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImovelCriarEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloImovelCriar)
                .addContainerGap(1139, Short.MAX_VALUE))
            .addGroup(ImovelCriarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ImovelCriarEditarLayout.createSequentialGroup()
                    .addGap(146, 146, 146)
                    .addComponent(criarImovelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(147, Short.MAX_VALUE)))
        );
        ImovelCriarEditarLayout.setVerticalGroup(
            ImovelCriarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImovelCriarEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloImovelCriar)
                .addContainerGap(698, Short.MAX_VALUE))
            .addGroup(ImovelCriarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ImovelCriarEditarLayout.createSequentialGroup()
                    .addGap(112, 112, 112)
                    .addComponent(criarImovelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(113, Short.MAX_VALUE)))
        );

        MainPanel.add(ImovelCriarEditar, "card2");

        lbTituloImovelExcluir.setText("Card - Imovel Editar/Listar/Excluir");

        javax.swing.GroupLayout ImovelExcluirListarLayout = new javax.swing.GroupLayout(ImovelExcluirListar);
        ImovelExcluirListar.setLayout(ImovelExcluirListarLayout);
        ImovelExcluirListarLayout.setHorizontalGroup(
            ImovelExcluirListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImovelExcluirListarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbTituloImovelExcluir)
                .addContainerGap(1086, Short.MAX_VALUE))
        );
        ImovelExcluirListarLayout.setVerticalGroup(
            ImovelExcluirListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImovelExcluirListarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbTituloImovelExcluir)
                .addContainerGap(680, Short.MAX_VALUE))
        );

        MainPanel.add(ImovelExcluirListar, "card2");

        jmSistema.setText("Sistema");

        jmSistemaTelaInicial.setText("Tela Inicial");
        jmSistema.add(jmSistemaTelaInicial);

        jmSistemaSair.setText("Sair");
        jmSistema.add(jmSistemaSair);

        jMenuBar.add(jmSistema);

        jmUsuario.setText("Usuário");

        jmUsuarioCriar.setText("Criar");
        jmUsuarioCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmUsuarioCriarActionPerformed(evt);
            }
        });
        jmUsuario.add(jmUsuarioCriar);

        jmUsuarioEditar.setText("Listar / Editar / Excluir");
        jmUsuario.add(jmUsuarioEditar);

        jMenuBar.add(jmUsuario);

        jmCliente.setText("Cliente");

        jmClienteCadastrar.setText("Cadastrar");
        jmCliente.add(jmClienteCadastrar);

        jmClienteEditar.setText("Listar / Editar / Excluir");
        jmClienteEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmClienteEditarActionPerformed(evt);
            }
        });
        jmCliente.add(jmClienteEditar);

        jMenuBar.add(jmCliente);

        jmImovel.setText("Imóvel");

        jmImovelCadastrar.setText("Cadastrar");
        jmImovel.add(jmImovelCadastrar);

        jmImovelEditar.setText("Listar / Editar / Excluir");
        jmImovel.add(jmImovelEditar);

        jMenuBar.add(jmImovel);

        jmContrato.setText("Contrato");

        jmContratoCriar.setText("Criar");
        jmContrato.add(jmContratoCriar);

        jmContratoListar.setText("Listar / Editar / Encerrar");
        jmContrato.add(jmContratoListar);

        jMenuBar.add(jmContrato);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmUsuarioCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmUsuarioCriarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmUsuarioCriarActionPerformed

    private void jmClienteEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmClienteEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmClienteEditarActionPerformed

    private void nomeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFieldActionPerformed

    private void idUsuarioFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idUsuarioFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idUsuarioFieldActionPerformed

    private void idContratoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idContratoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idContratoFieldActionPerformed

    private void imovelContratoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imovelContratoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imovelContratoFieldActionPerformed

    private void clienteContratoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteContratoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteContratoFieldActionPerformed

    private void statusContratoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusContratoFieldActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        try {
            String dataFinalString = dataFinalContratoTextField.getText();
            if (dataFinalString.trim().equals("") || dataFinalString.contains("_")){
                statusContratoField.setText("Data inválida");
                return;
            }
            
            Date dataFinal = sdf.parse(dataFinalString);
            Date hoje = new Date();
            
            if (hoje.after(dataFinal)){
                statusContratoField.setText("Inativo");
            } else {
                statusContratoField.setText("Ativo");
            }            
        }catch(Exception e){
            statusContratoField.setText("Erro");
            JOptionPane.showMessageDialog(this, "Formato de data inválido", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_statusContratoFieldActionPerformed

    private void idImovelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idImovelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idImovelFieldActionPerformed

    private void enderecoImovelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoImovelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoImovelFieldActionPerformed

    private void enviarContratoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarContratoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enviarContratoButtonActionPerformed

    private void tipoImovelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoImovelComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoImovelComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContratoCriarEditar;
    private javax.swing.JPanel ContratoExcluirListar;
    private javax.swing.JPanel ImovelCriarEditar;
    private javax.swing.JPanel ImovelExcluirListar;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel SistemaTelaInicial;
    private javax.swing.JPanel UsuarioCriarEditar;
    private javax.swing.JPanel UsuarioExcluirListar;
    private javax.swing.JButton cancelContratoButton;
    private javax.swing.JButton cancelImovelButton;
    private javax.swing.JButton cancelUsuarioButton;
    private javax.swing.JLabel cliente;
    private javax.swing.JTextField clienteContratoField;
    private javax.swing.JLabel cpf;
    private javax.swing.JLabel cpf1;
    private javax.swing.JFormattedTextField cpfField;
    private javax.swing.JPanel criarContratoPanel;
    private javax.swing.JPanel criarImovelPanel;
    private javax.swing.JPanel criarUsuarioPanel;
    private javax.swing.JLabel dataContrato;
    private javax.swing.JFormattedTextField dataContratoTextField;
    private javax.swing.JFormattedTextField dataFinalContratoTextField;
    private javax.swing.JLabel dataFinalizacao;
    private javax.swing.JLabel enderecoImovel;
    private javax.swing.JTextField enderecoImovelField;
    private javax.swing.JButton enviarContratoButton;
    private javax.swing.JButton enviarImovelButton;
    private javax.swing.JButton enviarUsuarioButton;
    private javax.swing.JLabel id;
    private javax.swing.JLabel idContrato;
    private javax.swing.JTextField idContratoField;
    private javax.swing.JLabel idImovel;
    private javax.swing.JTextField idImovelField;
    private javax.swing.JTextField idUsuarioField;
    private javax.swing.JTextField imovelContratoField;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jmCliente;
    private javax.swing.JMenuItem jmClienteCadastrar;
    private javax.swing.JMenuItem jmClienteEditar;
    private javax.swing.JMenu jmContrato;
    private javax.swing.JMenuItem jmContratoCriar;
    private javax.swing.JMenuItem jmContratoListar;
    private javax.swing.JMenu jmImovel;
    private javax.swing.JMenuItem jmImovelCadastrar;
    private javax.swing.JMenuItem jmImovelEditar;
    private javax.swing.JMenu jmSistema;
    private javax.swing.JMenuItem jmSistemaSair;
    private javax.swing.JMenuItem jmSistemaTelaInicial;
    private javax.swing.JMenu jmUsuario;
    private javax.swing.JMenuItem jmUsuarioCriar;
    private javax.swing.JMenuItem jmUsuarioEditar;
    private javax.swing.JLabel lbSistema;
    private javax.swing.JLabel lbTituloContratoCriar;
    private javax.swing.JLabel lbTituloContratoExcluir;
    private javax.swing.JLabel lbTituloImovelCriar;
    private javax.swing.JLabel lbTituloImovelExcluir;
    private javax.swing.JLabel lbTituloUsuarioCriar;
    private javax.swing.JLabel lbUsuarioExcluir;
    private javax.swing.JLabel nome;
    private javax.swing.JTextField nomeField;
    private javax.swing.JFormattedTextField precoField;
    private javax.swing.JLabel precoImovel;
    private javax.swing.JLabel statusContrato;
    private javax.swing.JTextField statusContratoField;
    private javax.swing.JLabel telefone;
    private javax.swing.JFormattedTextField telefoneField;
    private javax.swing.JLabel tipoImovel;
    private javax.swing.JComboBox<String> tipoImovelComboBox;
    // End of variables declaration//GEN-END:variables
}

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        ImageIcon imagemFundo = new ImageIcon(getClass().getResource("/rentsystem.png"));
        g.drawImage(imagemFundo.getImage(), 0, 0, getWidth(), getHeight(), this);
    }
    
    private void jmUsuarioCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmUsuarioCriarActionPerformed
        // TODO add your handling code here:
        cl.show(MainPanel, "UsuarioCriarEditar");

    }//GEN-LAST:event_jmUsuarioCriarActionPerformed

    private void jmClienteEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmClienteEditarActionPerformed
        // TODO add your handling code here:
        cl.show(MainPanel, "");

    }//GEN-LAST:event_jmClienteEditarActionPerformed

    private void btContratoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContratoEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btContratoEditarActionPerformed

    private void btImovelEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImovelEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btImovelEditarActionPerformed

    private void jmSistemaTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSistemaTelaInicialActionPerformed
        // TODO add your handling code here:
        cl.show(MainPanel, "SistemaTelaInicial");

    }//GEN-LAST:event_jmSistemaTelaInicialActionPerformed

    private void jmSistemaSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSistemaSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jmSistemaSairActionPerformed

    private void jmUsuarioEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmUsuarioEditarActionPerformed
        // TODO add your handling code here:
        cl.show(MainPanel, "UsuarioExcluirListar");

    }//GEN-LAST:event_jmUsuarioEditarActionPerformed

    private void jmImovelCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmImovelCadastrarActionPerformed
        // TODO add your handling code here:
        cl.show(MainPanel, "ImovelCriarEditar");

    }//GEN-LAST:event_jmImovelCadastrarActionPerformed

    private void jmImovelEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmImovelEditarActionPerformed
        // TODO add your handling code here:
        cl.show(MainPanel, "ImovelExcluirListar");

    }//GEN-LAST:event_jmImovelEditarActionPerformed

    private void jmContratoCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmContratoCriarActionPerformed
        // TODO add your handling code here:
        cl.show(MainPanel, "ContratoCriarEditar");

    }//GEN-LAST:event_jmContratoCriarActionPerformed

    private void jmContratoListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmContratoListarActionPerformed
        // TODO add your handling code here:
        cl.show(MainPanel, "ContratoExcluirListar");

    }//GEN-LAST:event_jmContratoListarActionPerformed

    private void MainPanelComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_MainPanelComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_MainPanelComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContratoCriarEditar;
    private javax.swing.JPanel ContratoExcluirListar;
    private javax.swing.JPanel ImovelCriarEditar;
    private javax.swing.JPanel ImovelExcluirListar;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel SistemaTelaInicial;
    private javax.swing.JPanel UsuarioCriarEditar;
    private javax.swing.JPanel UsuarioExcluirListar;
    private javax.swing.JButton btContratoEditar;
    private javax.swing.JButton btContratoExcluir;
    private javax.swing.JButton btContratoListar;
    private javax.swing.JButton btImovelEditar;
    private javax.swing.JButton btImovelExcluir;
    private javax.swing.JButton btImovelListar;
    private javax.swing.JButton btUsuarioEditar;
    private javax.swing.JButton btUsuarioExcluir;
    private javax.swing.JButton btUsuarioListar;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jlBoasVindas;
    private javax.swing.JMenu jmCliente;
    private javax.swing.JMenuItem jmClienteCadastrar;
    private javax.swing.JMenuItem jmClienteEditar;
    private javax.swing.JMenu jmContrato;
    private javax.swing.JMenuItem jmContratoCriar;
    private javax.swing.JMenuItem jmContratoListar;
    private javax.swing.JMenu jmImovel;
    private javax.swing.JMenuItem jmImovelCadastrar;
    private javax.swing.JMenuItem jmImovelEditar;
    private javax.swing.JMenu jmSistema;
    private javax.swing.JMenuItem jmSistemaSair;
    private javax.swing.JMenuItem jmSistemaTelaInicial;
    private javax.swing.JMenu jmUsuario;
    private javax.swing.JMenuItem jmUsuarioCriar;
    private javax.swing.JMenuItem jmUsuarioEditar;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbSistema;
    private javax.swing.JLabel lbTituloContratoCriar;
    private javax.swing.JLabel lbTituloContratoExcluir;
    private javax.swing.JLabel lbTituloImovelCriar;
    private javax.swing.JLabel lbTituloImovelExcluir;
    private javax.swing.JLabel lbUsuarioCriar;
    private javax.swing.JLabel lbUsuarioExcluir;
    private javax.swing.JPanel pnListarContratos;
    private javax.swing.JPanel pnListarImóvel;
    private javax.swing.JPanel pnListarUsuarios;
    private javax.swing.JTable tbContratoTabela;
    private javax.swing.JTable tbImovelTabela;
    private javax.swing.JTable tbUsuarioTabela;
    // End of variables declaration//GEN-END:variables
}
