package br.edu.iftm.pv_projetoimobiliaria_pt2.view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author AFSOUZA
 */
public class Telas extends javax.swing.JFrame {

    /**
     * Creates new form Telas
     */
    public Telas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        SistemaTelaInicial = new javax.swing.JPanel();
        lbSistema = new javax.swing.JLabel();
        UsuarioCriarEditar = new javax.swing.JPanel();
        lbUsuarioCriar = new javax.swing.JLabel();
        UsuarioExcluirListar = new javax.swing.JPanel();
        lbUsuarioExcluir = new javax.swing.JLabel();
        ContratoCriarEditar = new javax.swing.JPanel();
        lbTituloContratoCriar = new javax.swing.JLabel();
        ContratoExcluirListar = new javax.swing.JPanel();
        lbTituloContratoExcluir = new javax.swing.JLabel();
        ImovelCriarEditar = new javax.swing.JPanel();
        lbTituloImovelCriar = new javax.swing.JLabel();
        ImovelExcluirListar = new javax.swing.JPanel();
        lbTituloImovelExcluir = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jmSistema = new javax.swing.JMenu();
        jmSistemaTelaInicial = new javax.swing.JMenuItem();
        jmSistemaSair = new javax.swing.JMenuItem();
        jmUsuario = new javax.swing.JMenu();
        jmUsuarioCriar = new javax.swing.JMenuItem();
        jmUsuarioEditar = new javax.swing.JMenuItem();
        jmCliente = new javax.swing.JMenu();
        jmClienteCadastrar = new javax.swing.JMenuItem();
        jmClienteEditar = new javax.swing.JMenuItem();
        jmImovel = new javax.swing.JMenu();
        jmImovelCadastrar = new javax.swing.JMenuItem();
        jmImovelEditar = new javax.swing.JMenuItem();
        jmContrato = new javax.swing.JMenu();
        jmContratoCriar = new javax.swing.JMenuItem();
        jmContratoListar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));

        MainPanel.setPreferredSize(new java.awt.Dimension(1280, 720));
        MainPanel.setLayout(new java.awt.CardLayout());

        lbSistema.setText("Card - Tela Inicial");

        javax.swing.GroupLayout SistemaTelaInicialLayout = new javax.swing.GroupLayout(SistemaTelaInicial);
        SistemaTelaInicial.setLayout(SistemaTelaInicialLayout);
        SistemaTelaInicialLayout.setHorizontalGroup(
            SistemaTelaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SistemaTelaInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbSistema)
                .addContainerGap(1183, Short.MAX_VALUE))
        );
        SistemaTelaInicialLayout.setVerticalGroup(
            SistemaTelaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SistemaTelaInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbSistema)
                .addContainerGap(698, Short.MAX_VALUE))
        );

        MainPanel.add(SistemaTelaInicial, "card2");

        lbUsuarioCriar.setText("Card - Usuário");

        javax.swing.GroupLayout UsuarioCriarEditarLayout = new javax.swing.GroupLayout(UsuarioCriarEditar);
        UsuarioCriarEditar.setLayout(UsuarioCriarEditarLayout);
        UsuarioCriarEditarLayout.setHorizontalGroup(
            UsuarioCriarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioCriarEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbUsuarioCriar)
                .addContainerGap(1198, Short.MAX_VALUE))
        );
        UsuarioCriarEditarLayout.setVerticalGroup(
            UsuarioCriarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioCriarEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbUsuarioCriar)
                .addContainerGap(698, Short.MAX_VALUE))
        );

        MainPanel.add(UsuarioCriarEditar, "card2");

        lbUsuarioExcluir.setText("Card - Usuario Editar/Listar/Excluir");

        javax.swing.GroupLayout UsuarioExcluirListarLayout = new javax.swing.GroupLayout(UsuarioExcluirListar);
        UsuarioExcluirListar.setLayout(UsuarioExcluirListarLayout);
        UsuarioExcluirListarLayout.setHorizontalGroup(
            UsuarioExcluirListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioExcluirListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbUsuarioExcluir)
                .addContainerGap(1092, Short.MAX_VALUE))
        );
        UsuarioExcluirListarLayout.setVerticalGroup(
            UsuarioExcluirListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioExcluirListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbUsuarioExcluir)
                .addContainerGap(698, Short.MAX_VALUE))
        );

        MainPanel.add(UsuarioExcluirListar, "card2");

        lbTituloContratoCriar.setText("Card - Contrato Criar/Editar");

        javax.swing.GroupLayout ContratoCriarEditarLayout = new javax.swing.GroupLayout(ContratoCriarEditar);
        ContratoCriarEditar.setLayout(ContratoCriarEditarLayout);
        ContratoCriarEditarLayout.setHorizontalGroup(
            ContratoCriarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContratoCriarEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloContratoCriar)
                .addContainerGap(1128, Short.MAX_VALUE))
        );
        ContratoCriarEditarLayout.setVerticalGroup(
            ContratoCriarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContratoCriarEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloContratoCriar)
                .addContainerGap(698, Short.MAX_VALUE))
        );

        MainPanel.add(ContratoCriarEditar, "card2");

        lbTituloContratoExcluir.setText("Card - Contrato Editar/Listar/Excluir");

        javax.swing.GroupLayout ContratoExcluirListarLayout = new javax.swing.GroupLayout(ContratoExcluirListar);
        ContratoExcluirListar.setLayout(ContratoExcluirListarLayout);
        ContratoExcluirListarLayout.setHorizontalGroup(
            ContratoExcluirListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContratoExcluirListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloContratoExcluir)
                .addContainerGap(1085, Short.MAX_VALUE))
        );
        ContratoExcluirListarLayout.setVerticalGroup(
            ContratoExcluirListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContratoExcluirListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloContratoExcluir)
                .addContainerGap(698, Short.MAX_VALUE))
        );

        MainPanel.add(ContratoExcluirListar, "card2");

        lbTituloImovelCriar.setText("Card - Imovel Criar/Editar");

        javax.swing.GroupLayout ImovelCriarEditarLayout = new javax.swing.GroupLayout(ImovelCriarEditar);
        ImovelCriarEditar.setLayout(ImovelCriarEditarLayout);
        ImovelCriarEditarLayout.setHorizontalGroup(
            ImovelCriarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImovelCriarEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloImovelCriar)
                .addContainerGap(1139, Short.MAX_VALUE))
        );
        ImovelCriarEditarLayout.setVerticalGroup(
            ImovelCriarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImovelCriarEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloImovelCriar)
                .addContainerGap(698, Short.MAX_VALUE))
        );

        MainPanel.add(ImovelCriarEditar, "card2");

        lbTituloImovelExcluir.setText("Card - Imovel Editar/Listar/Excluir");

        javax.swing.GroupLayout ImovelExcluirListarLayout = new javax.swing.GroupLayout(ImovelExcluirListar);
        ImovelExcluirListar.setLayout(ImovelExcluirListarLayout);
        ImovelExcluirListarLayout.setHorizontalGroup(
            ImovelExcluirListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImovelExcluirListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloImovelExcluir)
                .addContainerGap(1096, Short.MAX_VALUE))
        );
        ImovelExcluirListarLayout.setVerticalGroup(
            ImovelExcluirListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImovelExcluirListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloImovelExcluir)
                .addContainerGap(698, Short.MAX_VALUE))
        );

        MainPanel.add(ImovelExcluirListar, "card2");

        jmSistema.setText("Sistema");

        jmSistemaTelaInicial.setText("Tela Inicial");
        jmSistema.add(jmSistemaTelaInicial);

        jmSistemaSair.setText("Sair");
        jmSistema.add(jmSistemaSair);

        jMenuBar.add(jmSistema);

        jmUsuario.setText("Usuário");

        jmUsuarioCriar.setText("Criar");
        jmUsuarioCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmUsuarioCriarActionPerformed(evt);
            }
        });
        jmUsuario.add(jmUsuarioCriar);

        jmUsuarioEditar.setText("Listar / Editar / Excluir");
        jmUsuario.add(jmUsuarioEditar);

        jMenuBar.add(jmUsuario);

        jmCliente.setText("Cliente");

        jmClienteCadastrar.setText("Cadastrar");
        jmCliente.add(jmClienteCadastrar);

        jmClienteEditar.setText("Listar / Editar / Excluir");
        jmClienteEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmClienteEditarActionPerformed(evt);
            }
        });
        jmCliente.add(jmClienteEditar);

        jMenuBar.add(jmCliente);

        jmImovel.setText("Imóvel");

        jmImovelCadastrar.setText("Cadastrar");
        jmImovel.add(jmImovelCadastrar);

        jmImovelEditar.setText("Listar / Editar / Excluir");
        jmImovel.add(jmImovelEditar);

        jMenuBar.add(jmImovel);

        jmContrato.setText("Contrato");

        jmContratoCriar.setText("Criar");
        jmContrato.add(jmContratoCriar);

        jmContratoListar.setText("Listar / Editar / Encerrar");
        jmContrato.add(jmContratoListar);

        jMenuBar.add(jmContrato);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmUsuarioCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmUsuarioCriarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmUsuarioCriarActionPerformed

    private void jmClienteEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmClienteEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmClienteEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContratoCriarEditar;
    private javax.swing.JPanel ContratoExcluirListar;
    private javax.swing.JPanel ImovelCriarEditar;
    private javax.swing.JPanel ImovelExcluirListar;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel SistemaTelaInicial;
    private javax.swing.JPanel UsuarioCriarEditar;
    private javax.swing.JPanel UsuarioExcluirListar;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jmCliente;
    private javax.swing.JMenuItem jmClienteCadastrar;
    private javax.swing.JMenuItem jmClienteEditar;
    private javax.swing.JMenu jmContrato;
    private javax.swing.JMenuItem jmContratoCriar;
    private javax.swing.JMenuItem jmContratoListar;
    private javax.swing.JMenu jmImovel;
    private javax.swing.JMenuItem jmImovelCadastrar;
    private javax.swing.JMenuItem jmImovelEditar;
    private javax.swing.JMenu jmSistema;
    private javax.swing.JMenuItem jmSistemaSair;
    private javax.swing.JMenuItem jmSistemaTelaInicial;
    private javax.swing.JMenu jmUsuario;
    private javax.swing.JMenuItem jmUsuarioCriar;
    private javax.swing.JMenuItem jmUsuarioEditar;
    private javax.swing.JLabel lbSistema;
    private javax.swing.JLabel lbTituloContratoCriar;
    private javax.swing.JLabel lbTituloContratoExcluir;
    private javax.swing.JLabel lbTituloImovelCriar;
    private javax.swing.JLabel lbTituloImovelExcluir;
    private javax.swing.JLabel lbUsuarioCriar;
    private javax.swing.JLabel lbUsuarioExcluir;
    // End of variables declaration//GEN-END:variables
}
