package br.edu.iftm.pv_projetoimobiliaria_pt2.view;

import java.awt.CardLayout;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author AFSOUZA
 */
public class Telas extends javax.swing.JFrame {
    
      
    CardLayout cl;
 



    /**
     * Creates new form Telas
     */
    public Telas() {
        initComponents();
    
        CardLayout cl = (CardLayout) MainPanel.getLayout();
        cl.show(MainPanel, "SistemaTelaInicial");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        SistemaTelaInicial = new javax.swing.JPanel();
        lbSistema = new javax.swing.JLabel();
        jlBoasVindas = new javax.swing.JLabel();
        lbLogo = new javax.swing.JLabel();
        UsuarioCriarEditar = new javax.swing.JPanel();
        lbUsuarioCriar = new javax.swing.JLabel();
        UsuarioExcluirListar = new javax.swing.JPanel();
        lbUsuarioExcluir = new javax.swing.JLabel();
        pnListarUsuarios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsuarioTabela = new javax.swing.JTable();
        btUsuarioListar = new javax.swing.JButton();
        btUsuarioEditar = new javax.swing.JButton();
        btUsuarioExcluir = new javax.swing.JButton();
        ContratoCriarEditar = new javax.swing.JPanel();
        lbTituloContratoCriar = new javax.swing.JLabel();
        ContratoExcluirListar = new javax.swing.JPanel();
        lbTituloContratoExcluir = new javax.swing.JLabel();
        pnListarContratos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbContratoTabela = new javax.swing.JTable();
        btContratoListar = new javax.swing.JButton();
        btContratoEditar = new javax.swing.JButton();
        btContratoExcluir = new javax.swing.JButton();
        ImovelCriarEditar = new javax.swing.JPanel();
        lbTituloImovelCriar = new javax.swing.JLabel();
        ImovelExcluirListar = new javax.swing.JPanel();
        lbTituloImovelExcluir = new javax.swing.JLabel();
        pnListarImóvel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbImovelTabela = new javax.swing.JTable();
        btImovelListar = new javax.swing.JButton();
        btImovelEditar = new javax.swing.JButton();
        btImovelExcluir = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jmSistema = new javax.swing.JMenu();
        jmSistemaTelaInicial = new javax.swing.JMenuItem();
        jmSistemaSair = new javax.swing.JMenuItem();
        jmUsuario = new javax.swing.JMenu();
        jmUsuarioCriar = new javax.swing.JMenuItem();
        jmUsuarioEditar = new javax.swing.JMenuItem();
        jmCliente = new javax.swing.JMenu();
        jmClienteCadastrar = new javax.swing.JMenuItem();
        jmClienteEditar = new javax.swing.JMenuItem();
        jmImovel = new javax.swing.JMenu();
        jmImovelCadastrar = new javax.swing.JMenuItem();
        jmImovelEditar = new javax.swing.JMenuItem();
        jmContrato = new javax.swing.JMenu();
        jmContratoCriar = new javax.swing.JMenuItem();
        jmContratoListar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));

        MainPanel.setPreferredSize(new java.awt.Dimension(1280, 720));
        MainPanel.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                MainPanelComponentAdded(evt);
            }
        });
        MainPanel.setLayout(new java.awt.CardLayout());

        lbSistema.setText("Card - Tela Inicial");

        jlBoasVindas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlBoasVindas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlBoasVindas.setText("<html>Bem-vindo ao Sistema de <br>Gerenciamento de  Imobiliárias - IMOB</html>");
        jlBoasVindas.setToolTipText("");

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rentsystem.png"))); // NOI18N

        javax.swing.GroupLayout SistemaTelaInicialLayout = new javax.swing.GroupLayout(SistemaTelaInicial);
        SistemaTelaInicial.setLayout(SistemaTelaInicialLayout);
        SistemaTelaInicialLayout.setHorizontalGroup(
            SistemaTelaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SistemaTelaInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SistemaTelaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SistemaTelaInicialLayout.createSequentialGroup()
                        .addComponent(lbSistema)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SistemaTelaInicialLayout.createSequentialGroup()
                        .addGap(0, 362, Short.MAX_VALUE)
                        .addComponent(jlBoasVindas, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(326, 326, 326))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SistemaTelaInicialLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbLogo)
                .addGap(512, 512, 512))
        );
        SistemaTelaInicialLayout.setVerticalGroup(
            SistemaTelaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SistemaTelaInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbSistema)
                .addGap(58, 58, 58)
                .addComponent(jlBoasVindas, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbLogo)
                .addContainerGap(275, Short.MAX_VALUE))
        );

        MainPanel.add(SistemaTelaInicial, "SistemaTelaInicial");

        lbUsuarioCriar.setText("Card - Usuário");

        javax.swing.GroupLayout UsuarioCriarEditarLayout = new javax.swing.GroupLayout(UsuarioCriarEditar);
        UsuarioCriarEditar.setLayout(UsuarioCriarEditarLayout);
        UsuarioCriarEditarLayout.setHorizontalGroup(
            UsuarioCriarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioCriarEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbUsuarioCriar)
                .addContainerGap(1198, Short.MAX_VALUE))
        );
        UsuarioCriarEditarLayout.setVerticalGroup(
            UsuarioCriarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioCriarEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbUsuarioCriar)
                .addContainerGap(698, Short.MAX_VALUE))
        );

        MainPanel.add(UsuarioCriarEditar, "UsuarioCriarEditar");

        lbUsuarioExcluir.setText("Card - Usuario Editar/Listar/Excluir");

        pnListarUsuarios.setBorder(javax.swing.BorderFactory.createTitledBorder("Listar Usuários"));

        tbUsuarioTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "UserName", "Nome", "Senha"
            }
        ));
        jScrollPane1.setViewportView(tbUsuarioTabela);

        btUsuarioListar.setText("Listar Usuários");

        btUsuarioEditar.setText("Editar");

        btUsuarioExcluir.setText("Excluir");

        javax.swing.GroupLayout pnListarUsuariosLayout = new javax.swing.GroupLayout(pnListarUsuarios);
        pnListarUsuarios.setLayout(pnListarUsuariosLayout);
        pnListarUsuariosLayout.setHorizontalGroup(
            pnListarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnListarUsuariosLayout.createSequentialGroup()
                .addGroup(pnListarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnListarUsuariosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btUsuarioEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btUsuarioExcluir))
                    .addGroup(pnListarUsuariosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btUsuarioListar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnListarUsuariosLayout.createSequentialGroup()
                .addGap(0, 85, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        pnListarUsuariosLayout.setVerticalGroup(
            pnListarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnListarUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btUsuarioListar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addGroup(pnListarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btUsuarioExcluir)
                    .addComponent(btUsuarioEditar))
                .addContainerGap())
        );

        javax.swing.GroupLayout UsuarioExcluirListarLayout = new javax.swing.GroupLayout(UsuarioExcluirListar);
        UsuarioExcluirListar.setLayout(UsuarioExcluirListarLayout);
        UsuarioExcluirListarLayout.setHorizontalGroup(
            UsuarioExcluirListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioExcluirListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbUsuarioExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UsuarioExcluirListarLayout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addComponent(pnListarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
        );
        UsuarioExcluirListarLayout.setVerticalGroup(
            UsuarioExcluirListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioExcluirListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbUsuarioExcluir)
                .addGap(38, 38, 38)
                .addComponent(pnListarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        MainPanel.add(UsuarioExcluirListar, "UsuarioExcluirListar");

        lbTituloContratoCriar.setText("Card - Contrato Criar/Editar");

        javax.swing.GroupLayout ContratoCriarEditarLayout = new javax.swing.GroupLayout(ContratoCriarEditar);
        ContratoCriarEditar.setLayout(ContratoCriarEditarLayout);
        ContratoCriarEditarLayout.setHorizontalGroup(
            ContratoCriarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContratoCriarEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloContratoCriar)
                .addContainerGap(1128, Short.MAX_VALUE))
        );
        ContratoCriarEditarLayout.setVerticalGroup(
            ContratoCriarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContratoCriarEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloContratoCriar)
                .addContainerGap(698, Short.MAX_VALUE))
        );

        MainPanel.add(ContratoCriarEditar, "ContratoCriarEditar");

        lbTituloContratoExcluir.setText("Card - Contrato Editar/Listar/Excluir");

        pnListarContratos.setBorder(javax.swing.BorderFactory.createTitledBorder("Listar Contratos"));

        tbContratoTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "ID_Imóvel", "Cliente", "Data_do_Contrato", "Data_da_Finalização", "Status"
            }
        ));
        jScrollPane2.setViewportView(tbContratoTabela);

        btContratoListar.setText("Listar Contratos");

        btContratoEditar.setText("Editar");
        btContratoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContratoEditarActionPerformed(evt);
            }
        });

        btContratoExcluir.setText("Excluir");

        javax.swing.GroupLayout pnListarContratosLayout = new javax.swing.GroupLayout(pnListarContratos);
        pnListarContratos.setLayout(pnListarContratosLayout);
        pnListarContratosLayout.setHorizontalGroup(
            pnListarContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnListarContratosLayout.createSequentialGroup()
                .addGroup(pnListarContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnListarContratosLayout.createSequentialGroup()
                        .addGap(0, 726, Short.MAX_VALUE)
                        .addComponent(btContratoEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btContratoExcluir))
                    .addGroup(pnListarContratosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btContratoListar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnListarContratosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        pnListarContratosLayout.setVerticalGroup(
            pnListarContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnListarContratosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btContratoListar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(pnListarContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btContratoExcluir)
                    .addComponent(btContratoEditar))
                .addContainerGap())
        );

        javax.swing.GroupLayout ContratoExcluirListarLayout = new javax.swing.GroupLayout(ContratoExcluirListar);
        ContratoExcluirListar.setLayout(ContratoExcluirListarLayout);
        ContratoExcluirListarLayout.setHorizontalGroup(
            ContratoExcluirListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContratoExcluirListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloContratoExcluir)
                .addContainerGap(1085, Short.MAX_VALUE))
            .addGroup(ContratoExcluirListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ContratoExcluirListarLayout.createSequentialGroup()
                    .addGap(191, 191, 191)
                    .addComponent(pnListarContratos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(191, Short.MAX_VALUE)))
        );
        ContratoExcluirListarLayout.setVerticalGroup(
            ContratoExcluirListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContratoExcluirListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloContratoExcluir)
                .addContainerGap(698, Short.MAX_VALUE))
            .addGroup(ContratoExcluirListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ContratoExcluirListarLayout.createSequentialGroup()
                    .addGap(104, 104, 104)
                    .addComponent(pnListarContratos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(104, Short.MAX_VALUE)))
        );

        MainPanel.add(ContratoExcluirListar, "ContratoExcluirListar");

        lbTituloImovelCriar.setText("Card - Imovel Criar/Editar");

        javax.swing.GroupLayout ImovelCriarEditarLayout = new javax.swing.GroupLayout(ImovelCriarEditar);
        ImovelCriarEditar.setLayout(ImovelCriarEditarLayout);
        ImovelCriarEditarLayout.setHorizontalGroup(
            ImovelCriarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImovelCriarEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloImovelCriar)
                .addContainerGap(1139, Short.MAX_VALUE))
        );
        ImovelCriarEditarLayout.setVerticalGroup(
            ImovelCriarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImovelCriarEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloImovelCriar)
                .addContainerGap(698, Short.MAX_VALUE))
        );

        MainPanel.add(ImovelCriarEditar, "ImovelCriarEditar");

        lbTituloImovelExcluir.setText("Card - Imovel Editar/Listar/Excluir");

        pnListarImóvel.setBorder(javax.swing.BorderFactory.createTitledBorder("Listar Imóveis"));

        tbImovelTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Endereço", "Preço", "Tipo"
            }
        ));
        jScrollPane3.setViewportView(tbImovelTabela);

        btImovelListar.setText("Listar Imóveis");

        btImovelEditar.setText("Editar");
        btImovelEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImovelEditarActionPerformed(evt);
            }
        });

        btImovelExcluir.setText("Excluir");

        javax.swing.GroupLayout pnListarImóvelLayout = new javax.swing.GroupLayout(pnListarImóvel);
        pnListarImóvel.setLayout(pnListarImóvelLayout);
        pnListarImóvelLayout.setHorizontalGroup(
            pnListarImóvelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnListarImóvelLayout.createSequentialGroup()
                .addGroup(pnListarImóvelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnListarImóvelLayout.createSequentialGroup()
                        .addGap(0, 726, Short.MAX_VALUE)
                        .addComponent(btImovelEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btImovelExcluir))
                    .addGroup(pnListarImóvelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btImovelListar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnListarImóvelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        pnListarImóvelLayout.setVerticalGroup(
            pnListarImóvelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnListarImóvelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btImovelListar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(pnListarImóvelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btImovelExcluir)
                    .addComponent(btImovelEditar))
                .addContainerGap())
        );

        javax.swing.GroupLayout ImovelExcluirListarLayout = new javax.swing.GroupLayout(ImovelExcluirListar);
        ImovelExcluirListar.setLayout(ImovelExcluirListarLayout);
        ImovelExcluirListarLayout.setHorizontalGroup(
            ImovelExcluirListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImovelExcluirListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloImovelExcluir)
                .addContainerGap(1096, Short.MAX_VALUE))
            .addGroup(ImovelExcluirListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ImovelExcluirListarLayout.createSequentialGroup()
                    .addGap(191, 191, 191)
                    .addComponent(pnListarImóvel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(191, Short.MAX_VALUE)))
        );
        ImovelExcluirListarLayout.setVerticalGroup(
            ImovelExcluirListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImovelExcluirListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloImovelExcluir)
                .addContainerGap(698, Short.MAX_VALUE))
            .addGroup(ImovelExcluirListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ImovelExcluirListarLayout.createSequentialGroup()
                    .addGap(104, 104, 104)
                    .addComponent(pnListarImóvel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(104, Short.MAX_VALUE)))
        );

        MainPanel.add(ImovelExcluirListar, "ImovelExcluirListar");

        jmSistema.setText("Sistema");

        jmSistemaTelaInicial.setText("Tela Inicial");
        jmSistemaTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSistemaTelaInicialActionPerformed(evt);
            }
        });
        jmSistema.add(jmSistemaTelaInicial);

        jmSistemaSair.setText("Sair");
        jmSistemaSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSistemaSairActionPerformed(evt);
            }
        });
        jmSistema.add(jmSistemaSair);

        jMenuBar.add(jmSistema);

        jmUsuario.setText("Usuário");

        jmUsuarioCriar.setText("Criar");
        jmUsuarioCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmUsuarioCriarActionPerformed(evt);
            }
        });
        jmUsuario.add(jmUsuarioCriar);

        jmUsuarioEditar.setText("Listar / Editar / Excluir");
        jmUsuarioEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmUsuarioEditarActionPerformed(evt);
            }
        });
        jmUsuario.add(jmUsuarioEditar);

        jMenuBar.add(jmUsuario);

        jmCliente.setText("Cliente");

        jmClienteCadastrar.setText("Cadastrar");
        jmCliente.add(jmClienteCadastrar);

        jmClienteEditar.setText("Listar / Editar / Excluir");
        jmClienteEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmClienteEditarActionPerformed(evt);
            }
        });
        jmCliente.add(jmClienteEditar);

        jMenuBar.add(jmCliente);

        jmImovel.setText("Imóvel");

        jmImovelCadastrar.setText("Cadastrar");
        jmImovelCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmImovelCadastrarActionPerformed(evt);
            }
        });
        jmImovel.add(jmImovelCadastrar);

        jmImovelEditar.setText("Listar / Editar / Excluir");
        jmImovelEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmImovelEditarActionPerformed(evt);
            }
        });
        jmImovel.add(jmImovelEditar);

        jMenuBar.add(jmImovel);

        jmContrato.setText("Contrato");

        jmContratoCriar.setText("Criar");
        jmContratoCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmContratoCriarActionPerformed(evt);
            }
        });
        jmContrato.add(jmContratoCriar);

        jmContratoListar.setText("Listar / Editar / Encerrar");
        jmContratoListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmContratoListarActionPerformed(evt);
            }
        });
        jmContrato.add(jmContratoListar);

        jMenuBar.add(jmContrato);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        MainPanel.getAccessibleContext().setAccessibleName("MainPanel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        ImageIcon imagemFundo = new ImageIcon(getClass().getResource("/rentsystem.png"));
        g.drawImage(imagemFundo.getImage(), 0, 0, getWidth(), getHeight(), this);
    }
    
    private void jmUsuarioCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmUsuarioCriarActionPerformed
        // TODO add your handling code here:
        cl.show(MainPanel, "UsuarioCriarEditar");

    }//GEN-LAST:event_jmUsuarioCriarActionPerformed

    private void jmClienteEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmClienteEditarActionPerformed
        // TODO add your handling code here:
        cl.show(MainPanel, "");

    }//GEN-LAST:event_jmClienteEditarActionPerformed

    private void btContratoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContratoEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btContratoEditarActionPerformed

    private void btImovelEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImovelEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btImovelEditarActionPerformed

    private void jmSistemaTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSistemaTelaInicialActionPerformed
        // TODO add your handling code here:
        cl.show(MainPanel, "SistemaTelaInicial");

    }//GEN-LAST:event_jmSistemaTelaInicialActionPerformed

    private void jmSistemaSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSistemaSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jmSistemaSairActionPerformed

    private void jmUsuarioEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmUsuarioEditarActionPerformed
        // TODO add your handling code here:
        cl.show(MainPanel, "UsuarioExcluirListar");

    }//GEN-LAST:event_jmUsuarioEditarActionPerformed

    private void jmImovelCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmImovelCadastrarActionPerformed
        // TODO add your handling code here:
        cl.show(MainPanel, "ImovelCriarEditar");

    }//GEN-LAST:event_jmImovelCadastrarActionPerformed

    private void jmImovelEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmImovelEditarActionPerformed
        // TODO add your handling code here:
        cl.show(MainPanel, "ImovelExcluirListar");

    }//GEN-LAST:event_jmImovelEditarActionPerformed

    private void jmContratoCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmContratoCriarActionPerformed
        // TODO add your handling code here:
        cl.show(MainPanel, "ContratoCriarEditar");

    }//GEN-LAST:event_jmContratoCriarActionPerformed

    private void jmContratoListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmContratoListarActionPerformed
        // TODO add your handling code here:
        cl.show(MainPanel, "ContratoExcluirListar");

    }//GEN-LAST:event_jmContratoListarActionPerformed

    private void MainPanelComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_MainPanelComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_MainPanelComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContratoCriarEditar;
    private javax.swing.JPanel ContratoExcluirListar;
    private javax.swing.JPanel ImovelCriarEditar;
    private javax.swing.JPanel ImovelExcluirListar;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel SistemaTelaInicial;
    private javax.swing.JPanel UsuarioCriarEditar;
    private javax.swing.JPanel UsuarioExcluirListar;
    private javax.swing.JButton btContratoEditar;
    private javax.swing.JButton btContratoExcluir;
    private javax.swing.JButton btContratoListar;
    private javax.swing.JButton btImovelEditar;
    private javax.swing.JButton btImovelExcluir;
    private javax.swing.JButton btImovelListar;
    private javax.swing.JButton btUsuarioEditar;
    private javax.swing.JButton btUsuarioExcluir;
    private javax.swing.JButton btUsuarioListar;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jlBoasVindas;
    private javax.swing.JMenu jmCliente;
    private javax.swing.JMenuItem jmClienteCadastrar;
    private javax.swing.JMenuItem jmClienteEditar;
    private javax.swing.JMenu jmContrato;
    private javax.swing.JMenuItem jmContratoCriar;
    private javax.swing.JMenuItem jmContratoListar;
    private javax.swing.JMenu jmImovel;
    private javax.swing.JMenuItem jmImovelCadastrar;
    private javax.swing.JMenuItem jmImovelEditar;
    private javax.swing.JMenu jmSistema;
    private javax.swing.JMenuItem jmSistemaSair;
    private javax.swing.JMenuItem jmSistemaTelaInicial;
    private javax.swing.JMenu jmUsuario;
    private javax.swing.JMenuItem jmUsuarioCriar;
    private javax.swing.JMenuItem jmUsuarioEditar;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbSistema;
    private javax.swing.JLabel lbTituloContratoCriar;
    private javax.swing.JLabel lbTituloContratoExcluir;
    private javax.swing.JLabel lbTituloImovelCriar;
    private javax.swing.JLabel lbTituloImovelExcluir;
    private javax.swing.JLabel lbUsuarioCriar;
    private javax.swing.JLabel lbUsuarioExcluir;
    private javax.swing.JPanel pnListarContratos;
    private javax.swing.JPanel pnListarImóvel;
    private javax.swing.JPanel pnListarUsuarios;
    private javax.swing.JTable tbContratoTabela;
    private javax.swing.JTable tbImovelTabela;
    private javax.swing.JTable tbUsuarioTabela;
    // End of variables declaration//GEN-END:variables
}
